[
  'bitcoin_change_address',
  'bitcoin_cold_storage',
  'bitcoin_tx_fee',
  'bitcoin_withdrawal_fee_percent',
  'clamcoin_change_address',
  'clamcoin_cold_storage',
  'clamcoin_tx_fee',
  'clamcoin_withdrawal_fee_percent',
  'quote_pct'
]
